---
settings:
  name: NetApp Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de automatización de NetApp
    url: "/index.html"
  - title: Novedades
    url: "/about/whats-new.html"
  - section: solutions
  - section: api
  - section: support
  - title: Avisos legales
    url: "/legal-notices.html"
