---
sidebar: sidebar 
permalink: about/whats-new.html 
keywords: whats new, enhancements, new features 
summary: NetApp actualiza regularmente las soluciones de automatización, las API DE REST de productos y el software relacionado para ofrecer nuevas funciones, mejoras y correcciones de errores. 
---
= Novedades de la automatización de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp actualiza regularmente las soluciones de automatización, las API DE REST de productos y el software relacionado para ofrecer nuevas funciones, mejoras y correcciones de errores.



== 27 de julio de 2023

.Cloud Volumes ONTAP
La compatibilidad con Cloud Volumes ONTAP está organizada por el entorno de cloud público. Se proporciona una nueva solución para el siguiente entorno de cloud:

* link:../solutions/cvo-gcp-burst-to-cloud.html["Cloud Volumes ONTAP para Google Cloud: Estallido a la nube"]




== 04 de junio de 2023

El https://console.netapp.com/automationCatalog["Catálogo de automatización de la consola de NetApp"^] Está disponible a través de la interfaz de usuario web de la consola.  El catálogo de automatización proporciona acceso a soluciones que pueden ayudarlo con la implementación y la integración automatizadas de los productos de NetApp .  La documentación de estas soluciones está organizada en varias áreas funcionales o de producto diferentes como se describe a continuación.

.Amazon FSx for NetApp ONTAP
Se proporcionan dos soluciones de administración de Amazon FSx for NetApp ONTAP de la siguiente manera:

* link:../solutions/fsxn-burst-to-cloud.html["Amazon FSx for NetApp ONTAP : Explosión a la nube"]
* link:../solutions/fsxn-disaster-recovery.html["Amazon FSx for NetApp ONTAP : recuperación ante desastres"]


.Azure NetApp Files
Se incluye una solución para ayudarle a poner en marcha Oracle con Azure NetApp Files:

* link:../solutions/anf-oracle.html["Oracle con Azure NetApp Files"]


.Cloud Volumes ONTAP
La compatibilidad con Cloud Volumes ONTAP está organizada por el entorno de cloud público. Las soluciones iniciales se proporcionan para dos entornos cloud de la siguiente manera:

* link:../solutions/cvo-aws-burst-to-cloud.html["AWS de Cloud Volumes ONTAP: Ráfagas en la nube"]
* link:../solutions/cvo-azure-burst-to-cloud.html["Cloud Volumes ONTAP Azure: Ráfagas a la nube"]

