---
sidebar: sidebar 
permalink: solutions/bac-overview.html 
keywords: bluexp automation catalog, automation catalog, overview, introduction 
summary: El catálogo de automatización de la consola de NetApp es una colección de soluciones de automatización disponibles para clientes, socios y empleados de NetApp .  El catálogo tiene varias características y beneficios. 
---
= Descripción general del catálogo de automatización de la consola de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El catálogo de automatización de la consola de NetApp es una colección de soluciones de automatización disponibles para clientes, socios y empleados de NetApp .  El catálogo tiene varias características y beneficios.

Ubicación única para sus necesidades de automatización:: Puedes acceder a la https://console.netapp.com/automationCatalog["Catálogo de automatización de la consola de NetApp"^] a través de la interfaz de usuario web de la consola.  Esto proporciona una única ubicación para los scripts, manuales y módulos necesarios para mejorar la automatización y el funcionamiento de sus productos y servicios de NetApp .
NetApp crea y prueba las soluciones:: Todas las soluciones de automatización y scripts han sido creadas y probadas por NetApp. Cada solución está dirigida a un caso de uso o solicitud específica de cliente. La mayor prioridad es la integración con los servicios de datos y archivos de NetApp.
Documentación:: Cada una de las soluciones de automatización incluye documentación asociada para ayudarle a comenzar.  Si bien se accede a las soluciones a través de la interfaz web de la Consola, toda la documentación está disponible en este sitio.  La documentación está organizada en función de los productos y servicios en la nube de NetApp .
Una base sólida para el futuro:: NetApp se compromete a ayudar a nuestros clientes a mejorar y optimizar la automatización de sus centros de datos y entornos de nube.  Esperamos seguir mejorando el catálogo de automatización de la consola para abordar los requisitos de los clientes, los cambios tecnológicos y la integración continua de productos.
Queremos tener noticias suyas:: El equipo de automatización de la Oficina de la experiencia del cliente de NetApp (CXO) le gustaría recibir noticias suyas. Si tiene algún comentario, problema o solicitud de características, envíe un correo electrónico a mailto:ng-cxo-automation-admins@NetApp.com[cxo automation team].

