---
sidebar: sidebar 
permalink: solutions/cvo-aws-burst-to-cloud.html 
keywords: bluexp automation catalog, netapp automation solutions, aws, cloud volumes ontap, burst to cloud 
summary: Este artículo respalda la solución NetApp Cloud Volumes ONTAP para AWS Automation, que está disponible para los clientes de NetApp desde el Catálogo de automatización de la consola de NetApp . 
---
= Cloud Volumes ONTAP para AWS: Estallido a la nube
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Este artículo respalda la solución NetApp Cloud Volumes ONTAP para AWS Automation, que está disponible para los clientes de NetApp desde el Catálogo de automatización de la consola de NetApp .

La solución de automatización de Cloud Volumes ONTAP para AWS automatiza la implementación en contenedores de Cloud Volumes ONTAP para AWS mediante Terraform, lo que le permite implementar Cloud Volumes ONTAP para AWS rápidamente, sin intervención manual.

.Antes de empezar
* Debes descargar ellink:https://console.netapp.com/automationCatalog["AWS de Cloud Volumes ONTAP: Ráfagas en la nube"^] Solución de automatización a través de la interfaz de usuario web de la consola.  La solución se presenta en el siguiente formato: `cvo_aws_flexcache.zip` .
* Debe instalar una máquina virtual Linux en la misma red que Cloud Volumes ONTAP.
* Después de instalar la máquina virtual Linux, debe seguir los pasos de esta solución para instalar las dependencias necesarias.




== Paso 1: Instalar Docker y Docker Compose



=== Instale Docker

Los siguientes pasos usan el software de distribución Linux Ubuntu 20,04 como ejemplo. Los comandos que ejecute dependen del software de distribución de Linux que utilice. Consulte la documentación específica del software de distribución de Linux para conocer la configuración.

.Pasos
. Instale Docker ejecutando los siguientes `sudo` comandos:
+
[source, cli]
----
sudo apt-get update
sudo apt-get install apt-transport-https cacertificates curl gnupg-agent software-properties-common curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
sudo apt-key add -
sudo add-apt-repository “deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable”
sudo apt-get update
sudo apt-get install dockerce docker-ce-cli containerd.io
----
. Compruebe la instalación:
+
[source, cli]
----
docker –version
----
. Compruebe que se ha creado un grupo denominado «docker» en su sistema Linux. Si es necesario, cree el grupo:
+
[source, cli]
----
sudo groupadd docker
----
. Agregue el usuario que necesita acceder a Docker al grupo:
+
[source, cli]
----
sudo usermod -aG docker $(whoami)
----
. Los cambios se aplican después de cerrar la sesión y volver a conectarse al terminal. Como alternativa, puede aplicar los cambios inmediatamente:
+
[source, cli]
----
newgrp docker
----




=== Instale Docker Compose

.Pasos
. Instale Docker Compose ejecutando los siguientes `sudo` comandos:
+
[source, cli]
----
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose
----
. Compruebe la instalación:
+
[source, cli]
----
docker-compose –version
----




== Paso 2: Preparar la imagen de Docker

.Pasos
. Copie `cvo_aws_flexcache.zip` la carpeta en la máquina virtual Linux que desee utilizar para implementar Cloud Volumes ONTAP:
+
[source, cli]
----
scp -i ~/<private-key>.pem -r cvo_aws_flexcache.zip <awsuser>@<IP_ADDRESS_OF_VM>:<LOCATION_TO_BE_COPIED>
----
+
** `private-key.pem` es su archivo de clave privada para iniciar sesión sin contraseña.
** `awsuser` Es el nombre de usuario de la máquina virtual.
** `IP_ADDRESS_OF_VM` Es la dirección IP del equipo virtual.
** `LOCATION_TO_BE_COPIED` es la ubicación donde se copiará la carpeta.


. Extraiga la `cvo_aws_flexcache.zip` carpeta. Puede extraer la carpeta en el directorio actual o en una ubicación personalizada.
+
Para extraer la carpeta del directorio actual, ejecute:

+
[source, cli]
----
unzip cvo_aws_flexcache.zip
----
+
Para extraer la carpeta en una ubicación personalizada, ejecute:

+
[source, cli]
----
unzip cvo_aws_flexcache.zip -d ~/<your_folder_name>
----
. Después de extraer el contenido, desplácese a la `CVO_Aws_Deployment` carpeta y ejecute el siguiente comando para ver los archivos:
+
[source, cli]
----
 ls -la
----
+
Debería ver una lista de archivos, similar al siguiente ejemplo:

+
[listing]
----
total 32
    drwxr-xr-x   8 user1  staff   256 Mar 23 12:26 .
    drwxr-xr-x   6 user1  staff   192 Mar 22 08:04 ..
    -rw-r--r--   1 user1  staff   324 Apr 12 21:37 .env
    -rw-r--r--   1 user1  staff  1449 Mar 23 13:19 Dockerfile
    drwxr-xr-x  15 user1  staff   480 Mar 23 13:19 cvo_Aws_source_code
    drwxr-xr-x   4 user1  staff   128 Apr 27 13:43 cvo_Aws_variables
    -rw-r--r--   1 user1  staff   996 Mar 24 04:06 docker-compose-deploy.yml
    -rw-r--r--   1 user1  staff  1041 Mar 24 04:06 docker-compose-destroy.yml
----
. Busque el `cvo_aws_flexcache_ubuntu_image.tar` archivo. Esto contiene la imagen de Docker necesaria para poner en marcha Cloud Volumes ONTAP para AWS.
. Abra el archivo:
+
[source, cli]
----
docker load -i cvo_aws_flexcache_ubuntu_image.tar
----
. Espere unos minutos hasta que se cargue la imagen de Docker y, a continuación, valide que la imagen de Docker se haya cargado correctamente:
+
[source, cli]
----
docker images
----
+
Debería ver una imagen de Docker llamada `cvo_aws_flexcache_ubuntu_image` con la `latest` etiqueta, como se muestra en el siguiente ejemplo:

+
[listing]
----
REPOSITORY                            TAG        IMAGE ID       CREATED      SIZE
 cvo_aws_flexcache_ubuntu_image     latest    18db15a4d59c   2 weeks ago   1.14GB
----
+

NOTE: Puede cambiar el nombre de la imagen de Docker si es necesario. Si cambia el nombre de la imagen de Docker, asegúrese de actualizar el nombre de la imagen de Docker en los `docker-compose-deploy` archivos y. `docker-compose-destroy`





== Paso 3: Crear archivos de variables de entorno

En esta etapa, debes crear dos archivos de variables de entorno.  Un archivo es para la autenticación de las API de AWS Resource Manager mediante las claves secretas y de acceso de AWS.  El segundo archivo sirve para configurar variables de entorno para permitir que los módulos Terraform de la consola localicen y autentiquen las API de AWS.

.Pasos
. Cree el `awsauth.env` archivo en la siguiente ubicación:
+
`path/to/env-file/awsauth.env`

+
.. Agregue el siguiente contenido al `awsauth.env` archivo:
+
access_key=<> clave_secreta=<>

+
El formato *debe* ser exactamente como se muestra arriba.



. Agregue la ruta de acceso absoluta al `.env` archivo.
+
Introduzca la ruta de acceso absoluta para `awsauth.env` el archivo de entorno que corresponda a la `AWS_CREDS` variable de entorno.

+
`AWS_CREDS=path/to/env-file/awsauth.env`

. Desplácese a `cvo_aws_variable` la carpeta y actualice el acceso y la clave secreta en el archivo de credenciales.
+
Agregue el siguiente contenido al archivo:

+
aws_access_key_id=<> aws_secret_access_key=<>

+
El formato *debe* ser exactamente como se muestra arriba.





== Paso 4: Regístrese en NetApp Intelligent Services

Regístrese en NetApp Intelligent Services a través de su proveedor de nube para pagar por hora (PAYGO) o mediante un contrato anual. Los servicios inteligentes de NetApp incluyen NetApp Backup and Recovery, Cloud Volumes ONTAP, NetApp Cloud Tiering, NetApp Ransomware Resilience y NetApp Disaster Recovery. La clasificación de datos de NetApp está incluida en su suscripción sin costo adicional.

.Pasos
. Desde el portal de Amazon Web Services (AWS), navegue a *SaaS* y seleccione *Suscribirse a NetApp Intelligent Services*.
+
Puede usar el mismo grupo de recursos que Cloud Volumes ONTAP o uno diferente.

. Configure el portal de la consola de NetApp para importar la suscripción de SaaS a la consola.
+
Puede configurarlo directamente desde el portal de AWS.

+
Serás redirigido al portal de la consola para confirmar la configuración.

. Confirme la configuración en el portal de la consola seleccionando *Guardar*.




== Paso 5: Cree un volumen externo

Debe crear un volumen externo para mantener los archivos de estado de Terraform y otros archivos importantes persistentes. Debe asegurarse de que los archivos están disponibles para Terraform para ejecutar el flujo de trabajo y las implementaciones.

.Pasos
. Cree un volumen externo fuera de Docker Compose:
+
[source, cli]
----
docker volume create <volume_name>
----
+
Ejemplo:

+
[listing]
----
docker volume create cvo_aws_volume_dst
----
. Utilice una de las siguientes opciones:
+
.. Añada una ruta de volumen externo al `.env` archivo de entorno.
+
Debe seguir el formato exacto que se muestra a continuación.

+
Formato:

+
`PERSISTENT_VOL=path/to/external/volume:/cvo_aws`

+
Ejemplo:
`PERSISTENT_VOL=cvo_aws_volume_dst:/cvo_aws`

.. Añada recursos compartidos NFS como volumen externo.
+
Asegúrese de que el contenedor de Docker se pueda comunicar con los recursos compartidos NFS y de que los permisos correctos, como lectura/escritura, están configurados.

+
... Agregue la ruta de acceso de recursos compartidos NFS como la ruta al volumen externo en el archivo Docker Compose, como se muestra a continuación: Formato:
+
`PERSISTENT_VOL=path/to/nfs/volume:/cvo_aws`

+
Ejemplo:
`PERSISTENT_VOL=nfs/mnt/document:/cvo_aws`





. Navegue a la `cvo_aws_variables` carpeta.
+
Debe ver el siguiente archivo de variables en la carpeta:

+
** `terraform.tfvars`
** `variables.tf`


. Cambie los valores dentro del `terraform.tfvars` archivo de acuerdo con sus requisitos.
+
Debe leer la documentación de soporte específica cuando modifique cualquiera de los valores de variables del `terraform.tfvars` archivo. Los valores pueden variar según la región, las zonas de disponibilidad y otros factores compatibles con Cloud Volumes ONTAP para AWS. Esto incluye licencias, tamaño de disco y tamaño de máquina virtual para nodos individuales y pares de alta disponibilidad.

+
Todas las variables de soporte para el agente de la consola y los módulos Terraform de Cloud Volumes ONTAP ya están definidas en el `variables.tf` archivo.  Debes hacer referencia a los nombres de las variables en el `variables.tf` archivo antes de agregarlo al `terraform.tfvars` archivo.

. En función de sus requisitos, puede activar o desactivar FlexCache and FlexClone configurando las siguientes opciones en `true` o `false`.
+
Los siguientes ejemplos habilitan FlexCache y FlexClone:

+
** `is_flexcache_required = true`
** `is_flexclone_required = true`






== Paso 6: Ponga en marcha Cloud Volumes ONTAP para AWS

Utilice los siguientes pasos para poner en marcha Cloud Volumes ONTAP para AWS.

.Pasos
. Desde la carpeta raíz, ejecute el siguiente comando para activar el despliegue:
+
[source, cli]
----
docker-compose -f docker-compose-deploy.yml up -d
----
+
Se activan dos contenedores, el primer contenedor pone en marcha Cloud Volumes ONTAP y el segundo contenedor envía datos de telemetría a AutoSupport.

+
El segundo contenedor espera hasta que el primer contenedor complete todos los pasos correctamente.

. Supervise el progreso del proceso de despliegue mediante los archivos log:
+
[source, cli]
----
docker-compose -f docker-compose-deploy.yml logs -f
----
+
Este comando proporciona resultados en tiempo real y captura los datos en los siguientes archivos de registro:
`deployment.log`

+
`telemetry_asup.log`

+
Puede cambiar el nombre de estos archivos de registro editando `.env` el archivo mediante las siguientes variables de entorno:

+
`DEPLOYMENT_LOGS`

+
`TELEMETRY_ASUP_LOGS`

+
Los siguientes ejemplos muestran cómo cambiar los nombres de los archivos log:

+
`DEPLOYMENT_LOGS=<your_deployment_log_filename>.log`

+
`TELEMETRY_ASUP_LOGS=<your_telemetry_asup_log_filename>.log`



.Después de terminar
Puede utilizar los siguientes pasos para eliminar el entorno temporal y limpiar los elementos creados durante el proceso de despliegue.

.Pasos
. Si implementó FlexCache, configure la siguiente opción en `terraform.tfvars` el archivo de variables, esto limpia los volúmenes de FlexCache y elimina el entorno temporal que se creó anteriormente.
+
`flexcache_operation = "destroy"`

+

NOTE: Las opciones posibles son  `deploy` y. `destroy`

. Si implementó FlexClone, configure la siguiente opción en `terraform.tfvars` el archivo de variables, esto limpia los volúmenes de FlexClone y elimina el entorno temporal que se creó anteriormente.
+
`flexclone_operation = "destroy"`

+

NOTE: Las opciones posibles son `deploy` y. `destroy`


