---
sidebar: sidebar 
permalink: solutions/fsxn-disaster-recovery.html 
keywords: bluexp automation catalog, netapp automation solutions, fsx for ontap, disaster recovery, backup, netapp console 
summary: Puedes utilizar esta solución de automatización para realizar un backup de recuperación ante desastres de un sistema de origen usando Amazon FSx para NetApp ONTAP. 
---
= Amazon FSx for NetApp ONTAP : recuperación ante desastres
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede utilizar esta solución de automatización para realizar una copia de seguridad de recuperación ante desastres de un sistema de origen mediante la administración de Amazon FSx for NetApp ONTAP .


NOTE: La administración de Amazon FSx for NetApp ONTAP también se conoce como *FSx para ONTAP*.

.Acerca de esta solución
En general, el código de automatización proporcionado con esta solución realiza las siguientes acciones:

* Aprovisionar un sistema de archivos FSx para ONTAP de destino
* Aprovisione las máquinas virtuales de almacenamiento (SVM) para el sistema de archivos
* Cree una relación de paridad de clústeres entre los sistemas de origen y destino
* Cree una relación entre iguales de SVM entre el sistema de origen y el de destino para SnapMirror
* Crear volúmenes de destino
* Crear una relación de SnapMirror entre los volúmenes de origen y de destino
* Inicie la transferencia de SnapMirror entre los volúmenes de origen y destino


La automatización se basa en Docker y Docker Compose que deben instalarse en la máquina virtual Linux como se describe a continuación.

.Antes de empezar
Debe tener lo siguiente para completar el aprovisionamiento y la configuración:

* Necesitas descargar el https://console.netapp.com/automationCatalog["Amazon FSx for NetApp ONTAP : recuperación ante desastres"^] Solución de automatización a través de la interfaz de usuario web de la consola NetApp .  La solución se presenta en el siguiente formato: `FSxN_DR.zip` .  Este zip contiene el `AWS_FSxN_Bck_Prov.zip` archivo que utilizará para implementar la solución descrita en este documento.
* Conectividad de red entre los sistemas de origen y destino.
* Una VM de Linux con las siguientes características:
+
** Distribución de Linux basada en Debian
** Puesto en marcha en el mismo subconjunto de VPC utilizado para el aprovisionamiento de FSx para ONTAP


* Una cuenta de AWS.




== Paso 1: Instale y configure Docker

Instalar y configurar Docker en una máquina virtual Linux basada en Debian.

.Pasos
. Preparar el entorno.
+
[source, cli]
----
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent softwareproperties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
----
. Instale Docker y verifique la instalación.
+
[source, cli]
----
sudo apt-get install docker-ce docker-ce-cli containerd.io
docker --version
----
. Añada el grupo Linux requerido con un usuario asociado.
+
Primero comprueba si el grupo *docker* existe en tu sistema Linux. Si no existe, cree el grupo y agregue el usuario. De forma predeterminada, el usuario de shell actual se agrega al grupo.

+
[source, cli]
----
sudo groupadd docker
sudo usermod -aG docker $(whoami)
----
. Active las nuevas definiciones de grupo y usuario
+
Si ha creado un nuevo grupo con un usuario, debe activar las definiciones. Para ello, puede cerrar la sesión de Linux y volver a iniciarla. O bien puede ejecutar el siguiente comando.

+
[source, cli]
----
newgrp docker
----




== Paso 2: Instale Docker Compose

Instale Docker Compose en una máquina virtual Linux basada en Debian.

.Pasos
. Instale Docker Compose.
+
[source, cli]
----
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
----
. Compruebe que la instalación se ha realizado correctamente.
+
[source, cli]
----
docker-compose --version
----




== Paso 3: Preparar la imagen de Docker

Debe extraer y cargar la imagen de Docker proporcionada con la solución de automatización.

.Pasos
. Copie el archivo de la solución `AWS_FSxN_Bck_Prov.zip` en la máquina virtual donde se ejecutará el código de automatización.
+
[source, cli]
----
scp -i ~/<private-key.pem> -r AWS_FSxN_Bck_Prov.zip user@<IP_ADDRESS_OF_VM>
----
+
El parámetro de entrada `private-key.pem` es el archivo de claves privadas utilizado para la autenticación de máquinas virtuales de AWS (instancia de EC2).

. Desplácese a la carpeta correcta con el archivo de solución y descomprima el archivo.
+
[source, cli]
----
unzip AWS_FSxN_Bck_Prov.zip
----
. Navegue a la nueva carpeta `AWS_FSxN_Bck_Prov` creada con la operación de descompresión y enumere los archivos. Debería ver el archivo `aws_fsxn_bck_image_latest.tar.gz`.
+
[source, cli]
----
ls -la
----
. Cargue el archivo de imagen de Docker. La operación de carga debería completarse normalmente en unos segundos.
+
[source, cli]
----
docker load -i aws_fsxn_bck_image_latest.tar.gz
----
. Confirme que se ha cargado la imagen de Docker.
+
[source, cli]
----
docker images
----
+
Deberías ver la imagen de Docker `aws_fsxn_bck_image` con la etiqueta `latest`.

+
[listing]
----
   REPOSITORY        TAG     IMAGE ID      CREATED      SIZE
aws_fsxn_bck_image  latest  da87d4974306  2 weeks ago  1.19GB
----




== Paso 4: Crear un archivo de entorno para las credenciales de AWS

Se debe crear un archivo de variable local para la autenticación mediante la clave secreta y de acceso. A continuación, agregue el archivo al `.env` archivo.

.Pasos
. Cree el `awsauth.env` archivo en la siguiente ubicación:
+
`path/to/env-file/awsauth.env`

. Agregue el siguiente contenido al archivo:
+
[listing]
----
access_key=<>
secret_key=<>
----
+
El formato *debe* ser exactamente como se muestra arriba sin ningún espacio entre `key` y. `value`

. Agregue la ruta de acceso absoluta al `.env` archivo mediante la `AWS_CREDS` variable. Por ejemplo:
+
`AWS_CREDS=path/to/env-file/awsauth.env`





== Paso 5: Cree un volumen externo

Necesita un volumen externo para asegurarse de que los archivos de estado de Terraform y otros archivos importantes son persistentes. Estos archivos deben estar disponibles para que Terraform ejecute el flujo de trabajo y las implementaciones.

.Pasos
. Cree un volumen externo fuera de Docker Compose.
+
Asegúrese de actualizar el nombre del volumen (último parámetro) al valor apropiado antes de ejecutar el comando.

+
[source, cli]
----
docker volume create aws_fsxn_volume
----
. Añada la ruta al volumen externo al `.env` archivo de entorno mediante el comando:
+
`PERSISTENT_VOL=path/to/external/volume:/volume_name`

+
Recuerde mantener el contenido del archivo existente y el formato de dos puntos. Por ejemplo:

+
[source, cli]
----
PERSISTENT_VOL=aws_fsxn_volume:/aws_fsxn_bck
----
+
En su lugar, se puede agregar un recurso compartido de NFS como volumen externo mediante un comando, como el siguiente:

+
`PERSISTENT_VOL=nfs/mnt/document:/aws_fsx_bck`

. Actualice las variables de Terraform.
+
.. Navegue a la carpeta `aws_fsxn_variables`.
.. Confirme que existen los dos archivos siguientes `terraform.tfvars`: Y `variables.tf`.
.. Actualice los valores en `terraform.tfvars` según sea necesario para el entorno.
+
Consulte https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_file_system["Recurso de Terraform: aws_fsx_ONTAP_file_system"^] para obtener más información.







== Paso 6: Implemente la solución de backup

Puede poner en marcha y aprovisionar la solución de backup de recuperación ante desastres.

.Pasos
. Navegue hasta la raíz de la carpeta (aws_FSxN_Bck_Prov) y ejecute el comando de provisionamiento.
+
[source, cli]
----
docker-compose up -d
----
+
Este comando crea tres contenedores. El primer contenedor pone en marcha FSx para ONTAP. El segundo contenedor crea la relación de iguales de clústeres, la relación entre iguales de SVM y el volumen de destino. El tercer contenedor crea la relación de SnapMirror e inicia la transferencia de SnapMirror.

. Supervisar el proceso de aprovisionamiento.
+
[source, cli]
----
docker-compose logs -f
----
+
Este comando le da la salida en tiempo real, pero se ha configurado para capturar los logs a través del archivo `deployment.log`. Puede cambiar el nombre de estos archivos log editando el `.env` archivo y actualizando las variables `DEPLOYMENT_LOGS`.


