---
sidebar: sidebar 
permalink: api/bluexp.html 
keywords: netapp products, product api, rest, rest api, bluexp, bluexp control plane 
summary: NetApp BlueXP es un plano de control unificado que proporciona una plataforma híbrida de múltiples nubes para administrar servicios de almacenamiento y datos en entornos locales y de nube pública.  Se compone de varios servicios o componentes distintos, cada uno de los cuales expone una API REST asociada.  Consulte la documentación y los recursos relacionados que se proporcionan a continuación para comenzar con la automatización de su entorno BlueXP . 
---
= Plano de control de BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP es un plano de control unificado que proporciona una plataforma híbrida de múltiples nubes para administrar servicios de almacenamiento y datos en entornos locales y de nube pública.  Se compone de varios servicios o componentes distintos, cada uno de los cuales expone una API REST asociada.  Consulte la documentación y los recursos relacionados que se proporcionan a continuación para comenzar con la automatización de su entorno BlueXP utilizando las API REST de BlueXP .

.API DE REST de BlueXP 
Puede utilizar las distintas API REST para automatizar la administración de sus servicios de almacenamiento y datos administrados por BlueXP.

* https://docs.netapp.com/us-en/bluexp-automation/["Documentación de la API de BlueXP"^]


.Familia BlueXP 
La documentación de la familia BlueXP  incluye todo lo que necesita para empezar a usar el plano de control de BlueXP .

* https://docs.netapp.com/us-en/bluexp-family/["Documentación de BlueXP"^]

